### ISSUE TITLE
Copy to clipboard support

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/elia#10]
This would use `pyperclip`.

Focus a message by clicking it or navigating via tab/shift+tab.

Press a keybind and the Markdown will be copied to your system clipboard.

**Comment by nowilton** [comment]
I would really like to see this function, can you tell me when it will be implemented?

**Comment by mkschreder** [comment]
Just make it copy to the system clipboard (xclip or something)

**Comment by darrenburns** [comment]
Added support for this in 1.0.0 via a terminal protocol. It's not supported in some environments and may be expanded to use pyperclip if it becomes and issue.
