### ISSUE TITLE
TextArea for Chat Input

### ISSUE THREAD

**Issue by juftin** [darrenburns/elia#18]
## Summary

[TextArea has landed](https://textual.textualize.io/widgets/text_area/) in Textual 0.38.0. This ticket is a **feature request** to update the [Input](https://github.com/darrenburns/elia/blob/f951560041e059fb8a84d80fea961a6f4b0e56e2/elia_chat/widgets/chat.py#L301) widget and replace it with a `TextArea` that supports multi-line input.

**Comment by juftin** [comment]
Thank you for TextArea Darren :tada: - it's seriously impressive. You're probably well ahead of me with this one. Let me know if not and I'm happy to look into implementing this.

**Comment by darrenburns** [comment]
Thank you @juftin - feel free to tackle this if you're interested in it! I might not get around to it for a bit.

**Comment by darrenburns** [comment]
I just released 1.0.0 which uses the TextArea widget for the input 😄
