### ISSUE TITLE
[improvement] localAI

### ISSUE THREAD

**Issue by rapha8l** [darrenburns/elia#20]
Hi, 
Thanks for elia !
Would it be possible to have localai support ?
Thanks again

**Comment by vorticalbox** [comment]
https://github.com/darrenburns/elia/pull/7

Is a good bet, if switched to langchain then you can very easily add models like llamba, gpt4 all.

This also allows the creation of doc stores so you can have your documents and ask the models about them.

Ive made a fork so I'll see if I can find some dev time for it.

**Comment by rapha8l** [comment]
thanks !

**Comment by darrenburns** [comment]
1.0.0 has added support for local LLMs.

**Comment by rapha8l** [comment]
Thanks !
