### ISSUE TITLE
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

### ISSUE THREAD

**Issue by yendefrr** [darrenburns/elia#29]
Runs
`pipx install elia-chat`
`elia`

Gets
`ValueError: the greenlet library is required to use this function. No module named 'greenlet'`

![Alacritty-yendefr@Yendefrs-MacBook-Air~Developersql-alerts@2x](https://github.com/darrenburns/elia/assets/91500932/1b0c7305-0269-4246-a0b4-dc44efac404f)

**Comment by darrenburns** [comment]
Thanks - seems like this was an undocumented requirement of SQLModel for using async on M1 Macs.

Should hopefully be fixed in 1.0.1. Could you try `pipx upgrade elia-chat` to install the latest version, and let me know if it's working for you now?

**Comment by darrenburns** [comment]
Tested on my M1 Macbook at work and it seems to fix it. Feel free to re-open if needed!

**Comment by yendefrr** [comment]
It works, thank you!
