### ISSUE TITLE
[Request] Authenticate Gemini via token

### ISSUE THREAD

**Issue by paw-lu** [darrenburns/elia#48]
Right now, based on instructions it seems like Gemini authentication relies on using some google cloud authentication process. Would it be possible to just use the Gemini API token like some other apps use?

**Comment by darrenburns** [comment]
If you set the `GEMINI_API_KEY` environment variable, it should work.

**Comment by paw-lu** [comment]
You're totally right—closing! (Curious—grepping through it seems you're not parsing the env variables yourself. Are they passed through another way?)

(btw really good interface here)

**Comment by darrenburns** [comment]
Most of the LLM stuff is handled in external libraries, and the env vars are quite standardised, so there's no parsing required - those libraries look for them themselves.

Thank you!
