### ISSUE TITLE
Setup for local ollama models

### ISSUE THREAD

**Issue by nossidge** [darrenburns/elia#53]
I do not understand how to set this up with my local ollama model.

Following the "[Running local models](https://github.com/darrenburns/elia?tab=readme-ov-file#running-local-models)" section of the readme, it says "The location of the configuration file is noted at the bottom of the options window (ctrl+o)". This leads me to try to run the program first, and I will then be able to find the config, by pressing ctrl+o. But I can't seem to run the program at all without an API key.

Running `elia` gives me this error:
```
Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it
```

So then I run with a dummy environment variable: `OPENAI_API_KEY=foo elia`

But then pressing ctrl+o does nothing at all.

Here's a screenshot:
![Screenshot from 2024-05-25 22-37-15](https://github.com/darrenburns/elia/assets/3586214/0119d4d2-7c54-4379-be0f-ec88af5db462)

How can I set up the config file for my local ollama `mistral` model?

Many thanks for your help.

**Comment by darrenburns** [comment]
You seem to be running a very old version - please run `pipx upgrade elia-chat` and let me know if you're still having issues

**Comment by nossidge** [comment]
Wow fast reply, thanks for the attentiveness, that's really cool!

But it seems like I'm already at the latest version 0.4.1:
![Screenshot from 2024-05-25 22-49-21](https://github.com/darrenburns/elia/assets/3586214/39ad0c35-376d-4fad-a861-ca96f3ac721a)

**Comment by darrenburns** [comment]
The latest version is 1.7.0 🙂

Maybe try a `pipx uninstall elia-chat` followed by an install?

**Comment by nossidge** [comment]
I'm still getting version 0.4.1 - I even tried re-installing `pipx`
![Screenshot from 2024-05-25 23-05-08](https://github.com/darrenburns/elia/assets/3586214/3a4a358e-ba3e-48bf-ab62-bcaa99cd8b37)
For clarity, I'm on Ubuntu 22.04.4 and Python 3.10.12, if that helps?
I don't know much about `pipx` requirements, I first installed it just now for this project!

**Comment by darrenburns** [comment]
Does 'pipx install elia-chat==1.7.0' work?

There are a few troubleshooting steps in this guide too - https://pipx.pypa.io/stable/troubleshooting/

If that doesn't work, maybe you'll have more luck with installing rye and doing "rye install elia-chat"

**Comment by m1chae1bx** [comment]
Hello, I got this after trying `pipx install elia-chat==1.7.0`

```
mbonon@mbonon-tm01926-mbp ~ % pipx install elia-chat==1.7.0
Fatal error from pip prevented installation. Full pip output in file:
    /Users/mbonon/.local/pipx/logs/cmd_2024-05-26_09.47.13_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 1.0.0 Requires-Python >=3.11; 1.0.0b1 Requires-Python >=3.11; 1.0.0b2 Requires-Python >=3.11; 1.0.1 Requires-Python >=3.11; 1.0.2 Requires-Python >=3.11; 1.0.3 Requires-Python >=3.11; 1.1.0 Requires-Python >=3.11; 1.1.1 Requires-Python >=3.11; 1.2.0 Requires-Python >=3.11; 1.3.0 Requires-Python >=3.11; 1.4.0 Requires-Python >=3.11; 1.5.0 Requires-Python >=3.11; 1.6.0 Requires-Python >=3.11; 1.6.1 Requires-Python >=3.11; 1.7.0 Requires-Python >=3.11
    ERROR: Could not find a version that satisfies the requirement elia-chat==1.7.0 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1)
    ERROR: No matching distribution found for elia-chat==1.7.0

Error installing elia-chat from spec 'elia-chat==1.7.0'.
```

**Comment by m1chae1bx** [comment]
I've figured out the problem. You need to install `pipx` while on python 3.11, and then run `pipx install elia-chat==1.7.0`

**Comment by m1chae1bx** [comment]
It still cannot find the api key even if I have already set it in an environment variable 
<img width="1511" alt="image" src="https://github.com/darrenburns/elia/assets/6761437/2638f0fd-8fc8-4988-83af-2b4fca0f06ba">

**Comment by m1chae1bx** [comment]
I got GPT-4o finally working but only if I run elia in the following way:

`OPENAI_API_KEY=<api key here> elia`

It doesn't work if I set it as an environment variable in a separate command.

**Comment by darrenburns** [comment]
You must not be exporting the environment variable correctly. How are you setting it?

**Comment by m1chae1bx** [comment]
You're right, my bad. I forgot to add the export keyword. I've only set it as `OPENAI_API_KEY=<api key here>` instead of `export OPENAI_API_KEY=<api key here>`

**Comment by nossidge** [comment]
Apparently pipx was using my system python, instead of my pyenv version.
Luckily there's a way to fix it, using the `PIPX_DEFAULT_PYTHON` to point at the pyenv shim:
```sh
PIPX_DEFAULT_PYTHON=/home/paul/.pyenv/shims/python pipx install elia-chat==1.7.0
```
It's now working perfectly, with my local LLM!

Thanks for bearing with me, as this issue really wasn't your fault at all.

**Comment by darrenburns** [comment]
Great, glad you sorted it!

No worries :)
