### ISSUE TITLE
Support for OpenRouter 

### ISSUE THREAD

**Issue by srajangarg** [darrenburns/elia#66]
[OpenRouter](https://openrouter.ai/docs/quick-start) is a  unified backend interface for LLMs.  Are there any plans to support it in elia?

**Comment by razem-io** [comment]
Just as an addition for anybody looking to setup openrouter instance via config. It would look like this:

```
default_model = "openrouter/anthropic/claude-3.5-sonnet:beta"

[[models]]
name = "openrouter/anthropic/claude-3.5-sonnet:beta"
display_name = "Claude Sonnet 3.5"
provider = "openrouter"
api_base = "https://openrouter.ai/api/v1"
api_key = "<your api key>"
```
