### ISSUE TITLE
Use in TMUX

### ISSUE THREAD

**Issue by jim-at-jibba** [darrenburns/elia#77]
The default keybinding to submit a question does not working in Tmux. Any ideas?

Thanks

**Comment by darrenburns** [comment]
You can use `alt+enter` too now as of `1.10.0`, assuming your terminal supports it.

Pretty soon, I'll add support for keymaps which will allow you to customise the keys as you wish.

**Comment by jim-at-jibba** [comment]
That's awesome. Thanks so much
