### ISSUE TITLE
Conversations stop working after token limit exceeded

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/elia#9]
Rather than sending the entire chat thread to the API, it should be truncated to ensure that we don't exceed the token limit of the chosen model.

As it stands, conversations will crash when the limit for the chosen model is exceeded.

@juftin Haven't dug into enough it but not sure if this would be covered by switching to langchain - perhaps it handles this 🤷

**Comment by juftin** [comment]
I don't believe Langchain is doing any limiting in #7 by default. I will look into this - there might be an easy way to handle this with tiktoken.

**Comment by darrenburns** [comment]
Just FYI, in case you weren't aware - the token lengths are already calculated using tiktoken and can be seen in the message info modal, I'm guessing that when a message is sent, we just need to iterate back through the messages and append as many of them to the conversation as the token limit will allow.

**Comment by darrenburns** [comment]
Should hopefully not be a problem in 1.0.0 🤞
